### ISSUE TITLE
netcdf lib & compiler must match, otherwise fail

### ISSUE THREAD

**Issue by ngam** [TRACMASS/Tracmass#3]
In your README.md file, [L37](https://github.com/TRACMASS/Tracmass/blob/4bf0fc66cc60fb9d559e070cbc96f4b833350a04/README.md?plain=1#L37), you make it sound like ensuring a netCDF4 library availability is enough. The fact is, the compiler and the netCDF4 library must match. Essentially, the netCDF4 (the Fortran version) library must be compiled with the compiler intended to compile the code. Otherwise, your automatic system of finding the netCDF4 module won't work. There are some workarounds: 1) One can work in a fresh container, installing both the compiler and netCDF4 module together; or 2) one could compile the netCDF4 library from scratch to match the intended compiler. Below is a quick example Singularity definition file to address the first scenario. I will try to report back if I find an easier solution that can work everywhere. Anyway, it may be worth adding this subtlety to your README.md (and website) so that potential users won't waste time trying to figure out why their system isn't working...

```
Bootstrap: docker
From: ubuntu:20.04

%post
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libnetcdf-dev libnetcdff-dev git curl vim make gfortran && \
    apt-get -y autoremove
```

**Comment by ngam** [comment]
I think your automated way (i.e. via nf-config) works fine if the netcdf-fortran library is loaded. Besides starting in a container, using the netcdf-fortran library from Spack was the only other way I could get this to work (and I tried on multiple devices with different architectures)

**Comment by ngam** [comment]
Another option is to get netcdf-fortran and gfortran from conda, then modify the Makefile replacing `nf-config --cflags` with `nf-config --fflags` on L54 --- why did you decide to call the `--cflags` here anyway with `automatic-44`? Kinda puzzling!

https://github.com/TRACMASS/Tracmass/blob/4bf0fc66cc60fb9d559e070cbc96f4b833350a04/Makefile#L51-L55

**Comment by joakimkjellsson** [comment]
Hi @ngam and @AitorAldama 

The logic behind this was that TRACMASS is usually used on either an HPC system or a regular workstation. 
The inspiration comes from the NEMO ocean model which includes a number of Makefiles for different machines. The user can then pick a Makefile that mostly resembles their system, modify it, and get going. 

On a "normal" Mac or Linux machine, the user probably has both gfortran and netcdf installed from some package manager (apt-get, Macports) so nfconfig and would give you everything you need to compile. 
On a HPC, the user likely runs "module load intel netcdf-intel" or something similar, which loads compilers and netcdf libs. Then nfconfig would also be perfectly fine to use, or at least I've never seen a case where it did not work. 

It's very difficult, if not impossible, to find a simple setting that will find the relevant netcdf libs automatically on all machines, which is why I think many users will need to adapt the Makefile to suit their needs. 

conda could of course be an option, and including TRACMASS inside some kind of package manger would be even better. 
However, I know this won't work for everyone either. For example, if you are on a HPC system that has a very low limit of the maximum number of inodes in the home directory. 

We can improve the Makefile commenting a bit and add some examples of what a user might do, for example: 
"If you are using a package manager (MacPorts, apt-get etc) then you can install gfortran and netcdf using...."
"If you are using a high-performance computer you will need to load the modules for the compilers and the matching netcdf libraries, e.g. module load intel and module load netcdf-intel."

Thanks for your suggestions!

Cheers
Joakim

**Comment by ngam** [comment]
Thank you for taking the time to respond. I appreciate it, and I appreciate your work on this.

> We can improve the Makefile commenting a bit and add some examples of what a user might do, for example:

I think this will help a lot. 

> On a "normal" Mac or Linux machine, the user probably has both gfortran and netcdf installed from some package manager (apt-get, Macports) so nfconfig and would give you everything you need to compile.
On a HPC, the user likely runs "module load intel netcdf-intel" or something similar, which loads compilers and netcdf libs. Then nfconfig would also be perfectly fine to use, or at least I've never seen a case where it did not work.

Actually, no. This was my problem. I tried on several machines (personal macos & ubuntu; and HPC rhel and suse) and I couldn't get it to work simply by following the instructions. Granted, I may have a weird/specific setup. I also want to make it clear this is not your fault; I brought this up to our technical HPC staff and they said they always dealt with inconsistent issues to do with netcdf. I believe there are two fundamental issues here at play:

1. It would be good to specify, very clearly, which netcdf library is actually needed (is it netcdf-c or netcdf-fortran? more and more systems have them separate now). I reckon in this case both are needed. Still it would be good to specify that explicitly. As an example, when I tried this --- many times --- by loading or directing the code to the intel libraries, it just failed (it couldn't compile). But when I tried with the spack.io netcdf-fortran library, it promptly compiled, but then failed to run because it wanted netcdf-c loaded. Then, with both netcdf-fortran and netcdf-c loaded, it all worked fine. This tells me your automated way is actually pretty good when the libraries are separate and compiled correctly (spack.io is notorious for attempting to compile and build everything from scratch to ensure compatibility).
2. In your automated setup (i.e. `nc-config` and `nf-config`), I am still unsure if it is actually correct, strictly speaking, to mix up the flags between `--flibs` and `--cflags`. Oftentimes, it will just work, but not on all systems and isolated envs I tried while debugging this. I think it may be more correct to have `--flibs` and `--fflags` here instead. In one system (conda; see above), it was stubborn and it never worked with the `--cflags` and all systems worked fine with the `--fflags`. 
https://github.com/TRACMASS/Tracmass/blob/4bf0fc66cc60fb9d559e070cbc96f4b833350a04/Makefile#L51-L55
I obviously don't know enough about this, and that's why I am reporting this as an issue here hoping to get more clarity, but also hopefully this code could be improved and made more usable in the process 🤞 

Again, I want to stress that I don't think this issue is your fault --- it is the confusion about netcdf libraries and how they're compiled. Thank you again and I am looking forward to using this model in the near future 😄
